letra = str(input('Digite algo '))
print('Seu tipo primitivo é',type(letra))
print('Pode ser convertida para numero ?', letra.isnumeric())
print('Contem letras ou numeros ?', letra.isalnum())
print('Todas as letras estão maiúsculas ?', letra.isupper())
print('Todas as letras estão minúsculas ?', letra.islower())
print('Contém casas decimais ?', letra.isdecimal())
print('Contém apenas espaço ?', letra.isspace())
print('Comtém apenas letras ?', letra.isalpha())
print('É uma string vazia ou contem ASCII', letra.isascii())
print('Todos os Os caracteres são digitos e contém pelo menos um caractere?',letra.isdigit())
print('Todos os caracteres são validos ?', letra.isidentifier())
print('Todos os caracteres podem ser impressos ou é uma string vazia ?',letra.isprintable())
print('Existe pelo menos um caractere maiusculo ou no começo ?',letra.istitle())